//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentProfessor
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class StudentProfessorEntities : DbContext
    {
        public StudentProfessorEntities()
            : base("name=StudentProfessorEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<courseTable> courseTables { get; set; }
        public virtual DbSet<studentEnrolTable> studentEnrolTables { get; set; }
        public virtual DbSet<studentTable> studentTables { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<tblProfessor> tblProfessors { get; set; }
    }
}
